# Generated by Django 4.2.1 on 2023-05-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epoc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('oxygenflow', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='P_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
