# Generated by Django 4.2.1 on 2023-05-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epoc_app', '0002_p_command_p_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='p_command',
            options={'ordering': ['pk']},
        ),
    ]
