# Generated by Django 4.2.1 on 2023-05-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epoc_app', '0004_alter_p_command_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='p_command',
            options={'ordering': ['pk']},
        ),
    ]
