# Generated by Django 4.2.1 on 2023-05-29 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epoc_app', '0005_alter_p_command_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_command',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
