# Generated by Django 4.2.1 on 2023-06-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epoc_app', '0007_patient_delete_t_vs_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
    ]
