# Generated by Django 4.2.1 on 2023-09-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epoc_app', '0010_alter_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_info',
            name='flow_real',
            field=models.FloatField(default=0),
        ),
    ]
