# Generated by Django 4.2.1 on 2023-09-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_created_by_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('attended', 'Attended'), ('waiting', 'Waiting')], default='waiting', max_length=20),
        ),
    ]
