# Generated by Django 4.2.1 on 2023-09-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('attended', 'Attended')], default='waiting', max_length=20),
        ),
    ]
